<?php include("/include/header.php"); ?>
<?php include("/include/navigation.php"); ?>
<?php include("/include/content1.php"); ?>
<?php include("/include/content2.php"); ?>
<?php include("/include/content3.php"); ?>
<?php include("/include/content4.php"); ?>
<?php include("/include/content5.php"); ?>
<?php include("/include/content6.php"); ?>
<?php include("/include/content7.php"); ?>
<?php include("/include/footer.php"); ?>
